app = "geo-demo"
primary_region = "sjc"
kill_signal = "SIGTERM"

[env]
  PHX_HOST = "geo-demo.fly.dev"
  PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 1

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [services.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
