defmodule Geo.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:countries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :citext
      add :slug, :citext

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :iso_code, :citext, null: false
      add :flag, :citext, null: false
    end

    create unique_index(:countries, [:iso_code], name: "countries_unique_iso_code_index")

    create unique_index(:countries, [:slug], name: "countries_unique_slug_index")
  end

  def down do
    drop_if_exists unique_index(:countries, [:slug], name: "countries_unique_slug_index")

    drop_if_exists unique_index(:countries, [:iso_code], name: "countries_unique_iso_code_index")

    drop table(:countries)
  end
end
